spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/esercizio-9
    username: root
    password: Spam123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
